from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import yaml


VALID_ROLES = {"queen", "specialist", "worker", "scout"}
VALID_SENIORITY = {"lead", "senior", "junior"}
VALID_RUN_MODES = {"sequential", "parallel"}


def _task_item_from_dict(name: str, item: dict) -> "TaskItem":
    """Build a TaskItem, tolerating unknown yml keys by filtering to known fields."""
    allowed = {f for f in TaskItem.__dataclass_fields__ if f != "name"}
    kwargs = {k: v for k, v in item.items() if k in allowed}
    return TaskItem(name=name, **kwargs)


def _parse_task(raw: dict) -> "TaskSpec":
    """Parse a task: section. Supports mono + multi (group | autogenerated)."""
    group_raw = raw.get("group")
    group: list[TaskItem] = []
    if isinstance(group_raw, dict):
        # group: { task_1: {file_path: ...}, task_2: {...} }
        for name, item in group_raw.items():
            if isinstance(item, dict):
                group.append(_task_item_from_dict(str(name), item))
            elif isinstance(item, str):
                group.append(TaskItem(name=str(name), file_path=item))
    elif isinstance(group_raw, list):
        # group: [ {name: task_1, file_path: ...}, ... ]
        for i, item in enumerate(group_raw):
            if isinstance(item, dict):
                name = str(item.get("name") or f"task_{i + 1}")
                group.append(_task_item_from_dict(name, item))
            elif isinstance(item, str):
                group.append(TaskItem(name=f"task_{i + 1}", file_path=item))
    elif group_raw is not None:
        raise ValueError(
            f"task.group must be dict or list, got {type(group_raw).__name__}"
        )

    allowed = set(TaskSpec.__dataclass_fields__)
    kwargs = {k: v for k, v in raw.items() if k in allowed and k != "group"}
    spec = TaskSpec(**kwargs)
    spec.group = group
    if spec.run_mode not in VALID_RUN_MODES:
        raise ValueError(
            f"task.run_mode '{spec.run_mode}' invalid — must be one of {sorted(VALID_RUN_MODES)}"
        )
    return spec


@dataclass
class AgentSpec:
    name: str
    type: str = "worker"
    role: str = "worker"
    seniority: str = "junior"
    prompt: Optional[str] = None
    prompt_path: Optional[str] = None
    # Soft DAG: this agent must wait for each listed agent's approval in
    # shared memory before starting work. Enforced via prompt-injected GATE
    # block, not OS-level scheduling — see FlowConfig.build_objective.
    depends_on: list[str] = field(default_factory=list)

    def validate(self):
        if self.role not in VALID_ROLES:
            raise ValueError(f"agent '{self.name}': invalid role '{self.role}' (must be one of {sorted(VALID_ROLES)})")
        if self.seniority not in VALID_SENIORITY:
            raise ValueError(f"agent '{self.name}': invalid seniority '{self.seniority}'")
        if not self.prompt and not self.prompt_path:
            raise ValueError(f"agent '{self.name}': must have 'prompt' or 'prompt_path'")
        # Normalize depends_on: yaml `null` → [], strings → reject explicitly,
        # non-string list items → reject. Also dedupe while preserving order.
        if self.depends_on is None:
            self.depends_on = []
        elif not isinstance(self.depends_on, list):
            raise ValueError(
                f"agent '{self.name}': depends_on must be a list of agent names, "
                f"got {type(self.depends_on).__name__}"
            )
        else:
            seen: set[str] = set()
            cleaned: list[str] = []
            for d in self.depends_on:
                if not isinstance(d, str):
                    raise ValueError(
                        f"agent '{self.name}': depends_on entries must be strings, "
                        f"got {type(d).__name__}"
                    )
                if d not in seen:
                    seen.add(d)
                    cleaned.append(d)
            self.depends_on = cleaned

    def resolved_prompt(self, base: Path) -> str:
        if self.prompt:
            return self.prompt.strip()
        if self.prompt_path:
            p = (base / self.prompt_path).expanduser().resolve()
            if not p.exists():
                raise FileNotFoundError(
                    f"agent '{self.name}': prompt_path not found: {p}"
                )
            return p.read_text(encoding="utf-8").strip()
        return ""


@dataclass
class SwarmSpec:
    topology: str = "hierarchical"
    max_agents: int = 8
    strategy: str = "specialized"
    consensus: str = "raft"


@dataclass
class MemorySpec:
    backend: str = "hybrid"
    namespace: str = "default"
    init: bool = True
    # How often agents should flush state to shared memory during a run.
    # 0 disables the periodic-checkpoint clause in the objective. Default 5m.
    checkpoint_interval_minutes: int = 5


@dataclass
class TaskItem:
    """A single subtask inside a multi-task group."""
    name: str
    file_path: Optional[str] = None
    content: Optional[str] = None  # inline alternative to file_path

    def resolved(self, base: Path) -> str:
        if self.content and self.content.strip():
            return self.content.strip()
        if self.file_path:
            p = (base / self.file_path).expanduser().resolve()
            if not p.exists():
                raise FileNotFoundError(
                    f"task '{self.name}': file_path not found: {p}"
                )
            return p.read_text(encoding="utf-8").strip()
        raise ValueError(f"task '{self.name}': needs file_path or content")


@dataclass
class TaskSpec:
    main: str = ""
    main_path: Optional[str] = None
    autonomous: bool = True
    max_iterations: int = 100
    timeout_minutes: int = 180

    # Multi-task mode
    multi: bool = False
    run_mode: str = "sequential"        # sequential | parallel
    autogenerated: bool = False          # let AI decompose `main` into subtasks
    autogen_count: int = 4               # how many subtasks to generate
    autogen_dir: str = ".rufler/tasks"          # where to write generated files
    autogen_file: str = ".rufler/tasks/auto_generated_task.yml"
    autogen_prompt: Optional[str] = None        # inline override for decomposer prompt
    autogen_prompt_path: Optional[str] = None   # md file override for decomposer prompt
    group: list[TaskItem] = field(default_factory=list)

    def resolved_main(self, base: Path) -> str:
        if self.main and self.main.strip():
            return self.main.strip()
        if self.main_path:
            p = (base / self.main_path).expanduser().resolve()
            if not p.exists():
                raise FileNotFoundError(f"task.main_path not found: {p}")
            return p.read_text(encoding="utf-8").strip()
        return ""

    def iter_tasks(self, base: Path) -> list[tuple[str, str]]:
        """Return [(name, resolved_body), ...].

        - mono mode → single (`main`, <resolved main>)
        - multi with group → one entry per item
        - multi autogenerated → caller must have populated group already.
        """
        if not self.multi:
            body = self.resolved_main(base)
            return [("main", body)] if body else []
        return [(item.name, item.resolved(base)) for item in self.group]


@dataclass
class ProjectSpec:
    name: str = "rufler-project"
    description: str = ""


@dataclass
class ExecutionSpec:
    """How `rufler start` should launch the Claude Code swarm.
    CLI flags override these values."""
    non_interactive: bool = False
    yolo: bool = False              # --dangerously-skip-permissions
    background: bool = False        # detach from terminal
    log_file: str = ".rufler/run.log"


@dataclass
class FlowConfig:
    project: ProjectSpec = field(default_factory=ProjectSpec)
    memory: MemorySpec = field(default_factory=MemorySpec)
    swarm: SwarmSpec = field(default_factory=SwarmSpec)
    task: TaskSpec = field(default_factory=TaskSpec)
    execution: ExecutionSpec = field(default_factory=ExecutionSpec)
    agents: list[AgentSpec] = field(default_factory=list)
    base_dir: Path = field(default_factory=Path.cwd)

    @classmethod
    def load(cls, path: Path) -> "FlowConfig":
        if not path.exists():
            raise FileNotFoundError(f"Config not found: {path}")
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        cfg = cls(base_dir=path.parent.resolve())
        if isinstance(data.get("project"), dict):
            cfg.project = ProjectSpec(**data["project"])
        if isinstance(data.get("memory"), dict):
            cfg.memory = MemorySpec(**data["memory"])
        if isinstance(data.get("swarm"), dict):
            cfg.swarm = SwarmSpec(**data["swarm"])
        if isinstance(data.get("task"), dict):
            cfg.task = _parse_task(data["task"])
        if isinstance(data.get("execution"), dict):
            cfg.execution = ExecutionSpec(**data["execution"])
        for a in data.get("agents") or []:
            spec = AgentSpec(**a)
            spec.validate()
            cfg.agents.append(spec)
        cfg._validate_dependencies()
        return cfg

    def _validate_dependencies(self) -> None:
        """Check depends_on references resolve to known agents and that the
        dependency graph has no cycles. Raises ValueError on either failure."""
        names = {a.name for a in self.agents}
        for a in self.agents:
            for dep in a.depends_on:
                if dep == a.name:
                    raise ValueError(f"agent '{a.name}': depends_on cannot reference itself")
                if dep not in names:
                    raise ValueError(
                        f"agent '{a.name}': depends_on '{dep}' is not a known agent "
                        f"(known: {sorted(names)})"
                    )
        # Cycle detection via DFS.
        graph = {a.name: list(a.depends_on) for a in self.agents}
        WHITE, GRAY, BLACK = 0, 1, 2
        color = {n: WHITE for n in graph}

        def visit(n: str, path: list[str]) -> None:
            if color[n] == GRAY:
                cycle = " -> ".join(path + [n])
                raise ValueError(f"agent dependency cycle: {cycle}")
            if color[n] == BLACK:
                return
            color[n] = GRAY
            for m in graph[n]:
                visit(m, path + [n])
            color[n] = BLACK

        for n in graph:
            visit(n, [])

    def build_objective(self, task_body: Optional[str] = None, task_name: str = "main") -> str:
        lines: list[str] = []
        lines.append(f"# PROJECT: {self.project.name}")
        if self.project.description:
            lines.append(self.project.description.strip())
        lines.append("")
        body = task_body if task_body is not None else self.task.resolved_main(self.base_dir)
        header = "MAIN TASK" if task_name == "main" else f"TASK: {task_name}"
        lines.append(f"# {header}")
        lines.append(body)
        lines.append("")
        lines.append(
            f"# AGENT TEAM ({len(self.agents)} agents)  "
            f"— coordinate via shared memory namespace '{self.memory.namespace}'"
        )
        lines.append("")

        # Sort lead > senior > junior for clarity
        order = {"lead": 0, "senior": 1, "junior": 2}
        sorted_agents = sorted(self.agents, key=lambda a: order.get(a.seniority, 99))

        ns = self.memory.namespace
        # Scope handoff keys per task so two parallel/sequential tasks sharing
        # the same agent set + memory namespace can't pick up each other's
        # briefs or approvals. `main` for mono mode keeps the keys readable.
        task_scope = task_name or "main"
        # Collect downstream map so we can tell each agent who is waiting on it.
        downstream: dict[str, list[str]] = {a.name: [] for a in self.agents}
        for a in self.agents:
            for dep in a.depends_on:
                if dep in downstream:
                    downstream[dep].append(a.name)

        for a in sorted_agents:
            header_extra = (
                f", depends_on={a.depends_on}" if a.depends_on else ""
            )
            lines.append(
                f"## {a.name}  [type={a.type}, role={a.role}, "
                f"seniority={a.seniority}{header_extra}]"
            )
            body = a.resolved_prompt(self.base_dir)
            lines.append(body if body else "(no prompt)")

            if a.depends_on:
                lines.append("")
                lines.append(f"### GATE — {a.name} MUST NOT start work until upstream agents approve")
                lines.append(
                    f"Before doing ANY work, read these keys from shared memory "
                    f"namespace '{ns}'. If any are missing, poll memory_search "
                    f"every ~30s and DO NOT write code, files, or decisions until "
                    f"all gates are open:"
                )
                for dep in a.depends_on:
                    lines.append(
                        f"  - memory_retrieve namespace='{ns}' "
                        f"key='instructions:{task_scope}:{dep}->{a.name}'  "
                        f"(your work brief from {dep}; required)"
                    )
                    lines.append(
                        f"  - memory_retrieve namespace='{ns}' "
                        f"key='approval:{task_scope}:{dep}->{a.name}'  "
                        f"(must equal 'approved' before you may proceed)"
                    )
                lines.append(
                    f"If a gate stays closed >10 minutes, write "
                    f"key='blockers' value='waiting on <upstream>' and keep polling. "
                    f"NEVER bypass a gate, even if you 'know what to do' — the "
                    f"upstream agent owns the contract."
                )

            waiters = downstream.get(a.name, [])
            if waiters:
                lines.append("")
                lines.append(f"### HANDOFF — downstream agents are blocked until {a.name} signs off")
                lines.append(
                    f"The following agents will not start until you publish their "
                    f"brief AND approval to shared memory namespace '{ns}': "
                    f"{', '.join(waiters)}."
                )
                for w in waiters:
                    lines.append(
                        f"  - memory_store namespace='{ns}' "
                        f"key='instructions:{task_scope}:{a.name}->{w}' "
                        f"value='<concrete work brief for {w}: scope, files, "
                        f"interfaces, acceptance criteria>'"
                    )
                    lines.append(
                        f"  - memory_store namespace='{ns}' "
                        f"key='approval:{task_scope}:{a.name}->{w}' value='approved'  "
                        f"(write this LAST, only after the brief is in place "
                        f"and you are confident {w} can proceed)"
                    )
                lines.append(
                    "If you must reject a downstream agent's request for approval, "
                    f"write value='rejected: <reason>' instead — they will halt "
                    f"and surface the blocker."
                )
            lines.append("")

        if self.task.autonomous:
            lines.append("# EXECUTION MODE: AUTONOMOUS")
            lines.append(
                "Work autonomously without asking for confirmation. "
                "Create all files, run builds, write tests, iterate until done. "
                "Use shared memory namespace above for cross-agent state."
            )
            lines.append("")

        # Resume awareness + periodic checkpointing. A previous rufler run may
        # have been interrupted — agents must probe shared memory for prior
        # progress AND continuously persist their own state so the next run
        # (or another agent) can recover.
        interval = self.memory.checkpoint_interval_minutes
        lines.append("# RESUME AWARENESS")
        lines.append(
            f"Before starting, search the shared memory namespace '{ns}' for "
            f"prior progress on this task. Look for keys like 'progress', "
            f"'checkpoint:latest', 'last_step', 'completed', 'decisions', "
            f"'blockers'. A previous run may have been interrupted — if you "
            f"find relevant state, continue from there instead of redoing work."
        )
        lines.append("")
        lines.append("# CHECKPOINT DISCIPLINE (do not skip — this is how we avoid losing work)")
        if interval > 0:
            lines.append(
                f"Write a checkpoint to shared memory namespace '{ns}' "
                f"EVERY {interval} MINUTES of wall-clock work, AND immediately "
                f"after completing any of: a file write, a test run, a build, "
                f"a sub-task, or a decision. A run can be killed at any moment "
                f"(terminal closed, power loss, SIGKILL) — anything not in "
                f"memory at the moment of the kill is lost forever."
            )
        else:
            lines.append(
                f"Write a checkpoint to shared memory namespace '{ns}' "
                f"immediately after completing any of: a file write, a test "
                f"run, a build, a sub-task, or a decision. A run can be killed "
                f"at any moment — anything not in memory is lost forever."
            )
        lines.append(
            "Use these exact keys so recovery is deterministic:"
        )
        lines.append(
            f"  - memory_store namespace='{ns}' key='checkpoint:latest' "
            f"value='<compact JSON: current_step, done_steps[], next_step, "
            f"open_questions[], last_ts>'"
        )
        lines.append(
            f"  - memory_store namespace='{ns}' key='checkpoint:<unix_ts>' "
            f"value='<same compact JSON>'  (timestamped snapshot for history)"
        )
        lines.append(
            f"  - memory_store namespace='{ns}' key='progress' "
            f"value='<one-line human summary: what is done, what is next>'"
        )
        lines.append(
            f"  - memory_store namespace='{ns}' key='decisions' "
            f"value='<list of design decisions made so far>'  (append as you go)"
        )
        lines.append(
            f"  - memory_store namespace='{ns}' key='blockers' "
            f"value='<anything stuck on, with context>'  (clear when unstuck)"
        )
        lines.append(
            "Rule of thumb: if you just spent >2 minutes on something you "
            "could not reconstruct from the repo alone, it MUST go into memory "
            "before your next tool call."
        )
        return "\n".join(lines)
