"""Autogenerated-task decomposer.

Given a big `main` task, ask `claude -p` to split it into N subtasks.
Writes each subtask as a markdown file under `tasks/` and emits a
companion yml (`auto_generated_task.yml`) that lists them in the
format `rufler` expects under `task.group`.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path
from typing import Optional

import yaml

from .templates import DENY_RULES_PROMPT

DEFAULT_DECOMPOSE_PROMPT = """\
# DECOMPOSER CONTRACT — READ FIRST

Output YAML directly in your response. Nothing else. No prose, no \
fences, no preamble, no "here is the plan".

**Do NOT use any tools.** No Glob, Grep, Read, Bash, Write, Task, or \
any other. The PROJECT ANALYSIS block below is complete — everything \
you need to plan is already there. Exploring the codebase wastes time \
and produces nothing. Generate the YAML and return.

## Required shape

```
project_summary: |
  15-30 lines distilling: what the project is, stack, key
  architectural decisions (cite modules from analysis), constraints,
  what success looks like. Downstream agents read only this block —
  empty or one-line summaries cause drift.

tasks:
  - name: task_1
    title: "Clear imperative title"
    content: |
      ## Scope
      What this subtask delivers. What it leaves for later. Meaningful
      unit of work — not a trivial slice.

      ## Files
      Concrete paths to create/modify, each with purpose + what
      changes. Several sentences per important file.

      ## Interfaces
      Signatures, types, DB shapes, migrations, events. The contract
      the next subtask relies on.

      ## Implementation notes
      Algorithms, libraries, patterns, gotchas — pulled from the
      analysis. Cite file:line. Name real modules. Several paragraphs.

      ## Tests
      What to add/update, where, unit vs integration, fixtures, edges.

      ## Acceptance criteria
      6-12 objectively verifiable checklist items ("POST /x returns
      201 on valid body and 422 on …", not "works correctly").

      ## Dependencies
      What earlier subtasks this builds on. What downstream consumers
      need from it.
  - name: task_2
    ...
```

## Constraints

- Exactly {n} subtasks. Sequential.
- Target 60-150 lines of `content` per task. Thin content ("implement \
backend", bare file lists) is a failure mode.
- Cover the MAIN TASK end-to-end. No gaps. No "polish" placeholders.
- Depth over breadth: prefer fewer deeper tasks over many shallow ones.

MAIN TASK (project analysis is included):
{main}
"""


def build_prompt(main_task: str, count: int, template: Optional[str] = None) -> str:
    """Render the decomposer prompt.

    If `template` is provided, it's used instead of the default. The template
    can reference `{n}` and `{main}` placeholders; if neither is present we
    append the main task block at the end so the LLM still sees it.

    We use plain `str.replace` instead of `str.format` so templates containing
    literal `{` / `}` (e.g. YAML inline flow or JSON examples) don't crash.
    """
    tpl = template if template is not None else DEFAULT_DECOMPOSE_PROMPT
    main_stripped = main_task.strip()
    if "{main}" not in tpl and "{n}" not in tpl:
        body = (
            f"{tpl.rstrip()}\n\nMAIN TASK:\n{main_stripped}\n\n"
            f"Generate exactly {count} subtasks."
        )
    else:
        body = tpl.replace("{n}", str(count)).replace("{main}", main_stripped)
    # DENY_RULES_PROMPT is always prepended, even when `template` is a
    # user-supplied custom prompt — rufler's own infrastructure must stay
    # off-limits regardless of what the user writes.
    return DENY_RULES_PROMPT + body


def _claude_bin() -> Optional[str]:
    return shutil.which("claude")


def _sanitize_fences(text: str) -> str:
    """Replace markdown fenced code blocks with YAML-safe equivalents.

    Models frequently wrap code examples inside ``content: |`` blocks
    with triple-backtick fences.  YAML's parser rejects bare `` ``` ``
    as an invalid token.  We convert opening fences (```lang) to a
    visible ``### code-block: lang`` marker and closing fences (```)
    to ``### end-code-block``, which are valid lines inside a literal
    block scalar.
    """
    out = []
    for ln in text.splitlines():
        stripped = ln.strip()
        if re.match(r"^```+\s*$", stripped):
            out.append(ln.replace(stripped, "# end-code-block"))
        elif re.match(r"^```+\w*", stripped):
            lang = stripped.lstrip("`").strip()
            marker = f"# code-block: {lang}" if lang else "# code-block"
            out.append(ln.replace(stripped, marker))
        else:
            out.append(ln)
    return "\n".join(out)


def _extract_yaml(text: str) -> str:
    """Pull a YAML document out of the model's reply.

    Anchors beat fences. When the YAML itself contains fenced code
    inside a ``content: |`` block (e.g. a directory tree, a code
    sample), a naive ``re.search(r"```...```")`` grabs the INNER fence
    and returns a non-YAML payload.  So we look for the top-level keys
    first, and only fall back to a yaml-tagged fence when no anchor is
    present.

    After extraction, ``_sanitize_fences`` converts any remaining
    triple-backtick lines into YAML comments so ``safe_load`` never
    chokes on them.

    Order:
    1. First top-level ``project_summary:`` or ``tasks:`` line — take
       everything from there to end.
    2. Otherwise a ```yaml / ```yml tagged fenced block (untagged ```
       fences are NOT matched — too easy to collide with nested code).
    3. Otherwise stripped raw text.
    """
    text = text.strip()
    lines = text.splitlines()
    for anchor in ("project_summary:", "tasks:"):
        for i, ln in enumerate(lines):
            if ln.lstrip().startswith(anchor):
                return _sanitize_fences("\n".join(lines[i:]).strip())
    m = re.search(r"```(?:yaml|yml)\s*\n(.*?)```", text, re.DOTALL)
    if m:
        return _sanitize_fences(m.group(1).strip())
    return _sanitize_fences(text)


def decompose(
    main_task: str,
    count: int,
    out_dir: Path,
    yml_path: Path,
    *,
    model: str = "sonnet",
    effort: str = "high",
    timeout: int = 600,
    prompt_template: Optional[str] = None,
    log_path: Optional[Path] = None,
) -> dict:
    """Call claude -p, parse YAML, write subtask files + companion yml.

    `prompt_template` optionally overrides the built-in decomposer prompt.
    It may include `{n}` and `{main}` placeholders.
    When *log_path* is given, claude's stream-json output is written to
    the NDJSON log in real time so ``rufler follow`` can show progress.

    Returns ``{"tasks": [...], "project_summary": "..."}``. `tasks` is
    the list of parsed subtasks (name, title, file_path). `project_summary`
    is the distilled north-star block the decomposer produces alongside —
    empty string if the model omitted it.
    """
    claude = _claude_bin()
    if not claude:
        raise RuntimeError("`claude` binary not found on PATH — can't decompose tasks.")

    prompt = build_prompt(main_task, count, prompt_template)
    cmd = [
        claude,
        "-p",
        "--model",
        model,
        "--effort",
        effort,
        "--output-format",
        "text",
        "--dangerously-skip-permissions",
        prompt,
    ]

    from .stream_log import stream_claude

    try:
        res = stream_claude(
            cmd, log_path=log_path, timeout=timeout, phase="decompose",
        )
    except subprocess.TimeoutExpired as e:
        raise RuntimeError(f"claude decompose timed out after {timeout}s: {e}") from e
    if res.returncode != 0:
        raise RuntimeError(
            f"claude decompose failed (rc={res.returncode}): {res.stderr[:400]}"
        )

    raw = _extract_yaml(res.stdout)
    try:
        parsed = yaml.safe_load(raw) or {}
    except yaml.YAMLError as e:
        raise RuntimeError(f"decomposer: invalid YAML from claude: {e}\n---\n{raw[:400]}") from e

    tasks = parsed.get("tasks") if isinstance(parsed, dict) else None
    if not isinstance(tasks, list) or not tasks:
        raise RuntimeError(
            f"decomposer: expected 'tasks:' list, got: {json.dumps(parsed)[:400]}"
        )

    project_summary = ""
    if isinstance(parsed, dict):
        ps_raw = parsed.get("project_summary")
        if isinstance(ps_raw, str):
            project_summary = ps_raw.strip()

    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[dict] = []
    for i, t in enumerate(tasks):
        if not isinstance(t, dict):
            continue
        name = str(t.get("name") or f"task_{i + 1}").strip()
        title = str(t.get("title") or name).strip()
        content = str(t.get("content") or "").strip()
        if not content:
            continue
        fp = out_dir / f"{name}.md"
        header = f"# {title}\n\n"
        fp.write_text(header + content + "\n", encoding="utf-8")
        written.append(
            {
                "name": name,
                "title": title,
                "file_path": str(fp.relative_to(yml_path.parent)),
            }
        )

    if not written:
        raise RuntimeError("decomposer: no valid subtasks produced")

    # Emit companion yml
    task_block: dict = {
        "multi": True,
        "run_mode": "sequential",
    }
    if project_summary:
        task_block["project_summary"] = project_summary
    task_block["group"] = [
        {"name": w["name"], "file_path": w["file_path"]} for w in written
    ]
    companion = {"task": task_block}
    yml_path.parent.mkdir(parents=True, exist_ok=True)
    yml_path.write_text(
        yaml.safe_dump(companion, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return {"tasks": written, "project_summary": project_summary}
