"""Autogenerated-task decomposer.

Given a big `main` task, ask `claude -p` to split it into N subtasks.
Writes each subtask as a markdown file under `tasks/` and emits a
companion yml (`auto_generated_task.yml`) that lists them in the
format `rufler` expects under `task.group`.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path
from typing import Optional

import yaml

DEFAULT_DECOMPOSE_PROMPT = """\
You are a task decomposer. Split the MAIN TASK below into exactly {n} \
sequential subtasks. Each subtask must be self-contained, actionable, and \
buildable on the previous one. Output ONLY valid YAML, no prose, no \
markdown fences, in this exact shape:

tasks:
  - name: task_1
    title: "Short human title"
    content: |
      Full multi-line description of the subtask. What to build, files to \
touch, acceptance criteria.
  - name: task_2
    title: "..."
    content: |
      ...

MAIN TASK:
{main}
"""


def build_prompt(main_task: str, count: int, template: Optional[str] = None) -> str:
    """Render the decomposer prompt.

    If `template` is provided, it's used instead of the default. The template
    can reference `{n}` and `{main}` placeholders; if neither is present we
    append the main task block at the end so the LLM still sees it.

    We use plain `str.replace` instead of `str.format` so templates containing
    literal `{` / `}` (e.g. YAML inline flow or JSON examples) don't crash.
    """
    tpl = template if template is not None else DEFAULT_DECOMPOSE_PROMPT
    main_stripped = main_task.strip()
    if "{main}" not in tpl and "{n}" not in tpl:
        return (
            f"{tpl.rstrip()}\n\nMAIN TASK:\n{main_stripped}\n\n"
            f"Generate exactly {count} subtasks."
        )
    return tpl.replace("{n}", str(count)).replace("{main}", main_stripped)


def _claude_bin() -> Optional[str]:
    return shutil.which("claude")


def _extract_yaml(text: str) -> str:
    """Pull a YAML document out of the model's reply.

    1. If there's a ```yaml fenced block, use it.
    2. Otherwise look for the first line beginning with `tasks:` and take
       everything from there to the end — the model may prepend prose.
    3. Fallback: return stripped raw text.
    """
    text = text.strip()
    m = re.search(r"```(?:yaml|yml)?\s*\n(.*?)```", text, re.DOTALL)
    if m:
        return m.group(1).strip()
    lines = text.splitlines()
    for i, ln in enumerate(lines):
        if ln.lstrip().startswith("tasks:"):
            return "\n".join(lines[i:]).strip()
    return text


def decompose(
    main_task: str,
    count: int,
    out_dir: Path,
    yml_path: Path,
    *,
    model: str = "sonnet",
    prompt_template: Optional[str] = None,
) -> list[dict]:
    """Call claude -p, parse YAML, write subtask files + companion yml.

    `prompt_template` optionally overrides the built-in decomposer prompt.
    It may include `{n}` and `{main}` placeholders.

    Returns the list of parsed subtasks (name, title, content, file_path).
    """
    claude = _claude_bin()
    if not claude:
        raise RuntimeError("`claude` binary not found on PATH — can't decompose tasks.")

    prompt = build_prompt(main_task, count, prompt_template)
    cmd = [
        claude,
        "-p",
        "--model",
        model,
        "--output-format",
        "text",
        "--dangerously-skip-permissions",
        prompt,
    ]
    try:
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    except subprocess.TimeoutExpired as e:
        raise RuntimeError(f"claude decompose timed out after 300s: {e}") from e
    if res.returncode != 0:
        raise RuntimeError(
            f"claude decompose failed (rc={res.returncode}): {res.stderr[:400]}"
        )

    raw = _extract_yaml(res.stdout)
    try:
        parsed = yaml.safe_load(raw) or {}
    except yaml.YAMLError as e:
        raise RuntimeError(f"decomposer: invalid YAML from claude: {e}\n---\n{raw[:400]}") from e

    tasks = parsed.get("tasks") if isinstance(parsed, dict) else None
    if not isinstance(tasks, list) or not tasks:
        raise RuntimeError(
            f"decomposer: expected 'tasks:' list, got: {json.dumps(parsed)[:400]}"
        )

    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[dict] = []
    for i, t in enumerate(tasks):
        if not isinstance(t, dict):
            continue
        name = str(t.get("name") or f"task_{i + 1}").strip()
        title = str(t.get("title") or name).strip()
        content = str(t.get("content") or "").strip()
        if not content:
            continue
        fp = out_dir / f"{name}.md"
        header = f"# {title}\n\n"
        fp.write_text(header + content + "\n", encoding="utf-8")
        written.append(
            {
                "name": name,
                "title": title,
                "file_path": str(fp.relative_to(yml_path.parent)),
            }
        )

    if not written:
        raise RuntimeError("decomposer: no valid subtasks produced")

    # Emit companion yml
    companion = {
        "task": {
            "multi": True,
            "run_mode": "sequential",
            "group": [
                {"name": w["name"], "file_path": w["file_path"]} for w in written
            ],
        }
    }
    yml_path.parent.mkdir(parents=True, exist_ok=True)
    yml_path.write_text(
        yaml.safe_dump(companion, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return written
